[build]
  command = "hugo --gc --minify -b $URL --logLevel debug --printI18nWarnings --printPathWarnings"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.152.1"
  GO_VERSION = "1.21.5"
  NODE_VERSION = "22"
  HUGO_ENABLEGITINFO = "true"
  HUGO_LOG_I18N_WARNINGS = "true"
  HUGO_LOG_WARNINGS = "true"
  FORCE_COLOR = "1"
  PNPM_LOG_LEVEL = "debug"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = """
    set -e
    echo "=== Deploy Preview Build ==="
    echo "Deploy URL: $DEPLOY_PRIME_URL"
    pnpm install --verbose
    hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --logLevel debug --printI18nWarnings --printPathWarnings
    pnpm dlx pagefind --source 'public' --verbose
  """

[context.branch-deploy]
  command = """
    set -e
    echo "=== Branch Deploy Build ==="
    echo "Deploy URL: $DEPLOY_PRIME_URL"
    pnpm install --verbose
    hugo --gc --minify -b $DEPLOY_PRIME_URL --logLevel debug --printI18nWarnings --printPathWarnings
    pnpm dlx pagefind --source 'public' --verbose
  """

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
